<?php

function lightning_umn_dlite_preprocess_field(&$variables) {
  if ($variables['field_name'] === 'field_dl_tags') {
    $variables['attributes']['class'][] = 'flex-display-list';
    foreach ($variables['items'] as $item) {
      $item['attributes']->addClass('flex-display-list-item');
    }
  }
}

/**
 * Implements hook_shortcut_default_set().
 */
function lightning_umn_dlite_shortcut_default_set($account) {
  return 'dl_shortcuts';
}